# Generated by Django 4.2.5 on 2023-09-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_rename_approvals_approval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approval',
            new_name='Approvals',
        ),
    ]
