# Generated by Django 4.2.5 on 2023-09-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_rename_approval_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='gender',
        ),
    ]
