# Generated by Django 4.2.5 on 2023-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_remove_approvals_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='firstname',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='applicantincome',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='area',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='coapplicatincome',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='credithistory',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='dependants',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='graduatededucation',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='loanamt',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='loanterm',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='married',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='selfemployed',
        ),
        migrations.AddField(
            model_name='approvals',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
