# Generated by Django 4.2.5 on 2023-09-08 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_house_delete_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
