# Generated by Django 4.2.5 on 2023-09-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_rename_sqft_house_sqft_living_house_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
