# Generated by Django 4.2.5 on 2023-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_house_estprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='fullAddress',
            field=models.CharField(default='UNK', max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
