# Generated by Django 4.2.5 on 2023-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_house_fulladdress_alter_house_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
